POST http://localhost:3003/api/blogs
Content-Type: application/json

  {
    "_id": "5a422bc61b54a676234d17fc",
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2,
    "__v": 0
  }